; Small C HuC6280 (v0.2, 08/Nov/97)
;
; Taken to HuC (22/Feb/00)
;
;
; This file generated by HuC (v3.21, 2005/04/09, Denki release)
; on Thu Apr 23 22:15:43 2015
;

HUC	= 1

	.include "startup.asm"
	.data
	.bank DATA_BANK

	.code

	.proc _spr_make
	__pushw
	__ldw_s	14
	  call	_spr_set
	__ldw_s	12
	  call	_spr_x
	__ldw_s	10
	  call	_spr_y
	__ldw_s	8
	  call	_spr_pattern
	__ldw_s	6
	  stx	_al
	__ldw_s	4
	  call	_spr_ctrl.2
	__ldw_s	2
	  call	_spr_pal
	__ldw_s	0
	  call	_spr_pri
LL1:

	__addmi	16,__stack
	  rts
	.endp

	.proc _spr_put
	__pushw
	__ldw_s	6
	  call	_spr_set
	__ldw_s	4
	  call	_spr_x
	__ldw_s	2
	  call	_spr_y
	__ldw_s	0
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL3
	__ldwi	8
	  stx	_al
	__ldwi	8
	  call	_spr_ctrl.2
	__lbra	LL4
LL3:

	__ldwi	8
	  stx	_al
	__ldwi	0
	  call	_spr_ctrl.2
LL4:

LL2:

	__addmi	8,__stack
	  rts
	.endp

	.data
	.dw $0
_alice:
	.incspr "alice.pcx",0,0,2,20
	.code
	.data
	.dw $0
_alicepal:
	.incpal "alice.pcx"
	.code
	.data
	.dw $0
_lapin:
	.incspr "lapin.pcx",0,0,2,20
	.code
	.data
	.dw $0
_lapinpal:
	.incpal "lapin.pcx"
	.code
	.data
	.dw $0
_ball:
	.incspr "ball.pcx",0,0,1,1
	.code
	.data
	.dw $0
_ballpal:
	.incpal "ball.pcx"
	.code
	.data
	.dw $0800
_scene_chr:
	.incchr "background_ground.pcx"
	.code
	.data
	.dw $0
_scene_pal:
	.incpal "background_ground.pcx"
	.code
	.data
	.dw $0
_scene_bat:
	.incbat "background_ground.pcx",4096,32,28
	.code
	.proc _main
	__ldwi	0
	__pushw
	__ldwi	180
	__pushw
	__ldwi	121
	__pushw
	__ldwi	20480
	__pushw
	__ldwi	57
	__pushw
	__ldwi	57
	__pushw
	__ldwi	0
	__pushw
	__ldwi	1
	  call	_spr_make
	_set_sprpal	#0,_lapinpal,#1
	__ldwi	20480
	__stw	_di
	__farptr	_lapin,_bl,_si
	__ldwi	2560
	__stw	_cx
	  call	_load_vram.3
	__ldwi	1
	__pushw
	__ldwi	52
	__pushw
	__ldwi	121
	__pushw
	__ldwi	25088
	__pushw
	__ldwi	185
	__pushw
	__ldwi	49
	__pushw
	__ldwi	1
	__pushw
	__ldwi	1
	  call	_spr_make
	_set_sprpal	#1,_alicepal,#1
	__ldwi	24576
	__stw	_di
	__farptr	_alice,_bl,_si
	__ldwi	2560
	__stw	_cx
	  call	_load_vram.3
	__ldwi	2
	__pushw
	__ldwi	200
	__pushw
	__ldwi	100
	__pushw
	__ldwi	23040
	__pushw
	__ldwi	185
	__pushw
	__ldwi	0
	__pushw
	__ldwi	2
	__pushw
	__ldwi	1
	  call	_spr_make
	_set_sprpal	#2,_ballpal,#1
	__ldwi	23040
	__stw	_di
	__farptr	_ball,_bl,_si
	__ldwi	256
	__stw	_cx
	  call	_load_vram.3
	_load_background	_scene_chr,_scene_pal,_scene_bat,#32,#28
	__ldwi	0
	__stw	_counter
	__ldwi	0
	__stw	_tics_alice
	__ldwi	0
	__stw	_frame_alice
	__ldwi	0
	__stw	_state_alice
	__ldwi	0
	__stw	_tics_lapin
	__ldwi	0
	__stw	_frame_lapin
	__ldwi	0
	__stw	_state_lapin
	__ldwi	52
	__stw	_alice_x
	__ldwi	180
	__stw	_lapin_x
	__ldwi	121
	__stw	_alice_y
	__ldwi	121
	__stw	_lapin_y
	__ldwi	0
	__stw	_alice_v
	__ldwi	0
	__stw	_lapin_v
	__ldwi	2
	  stx	_dir_alice
	__ldwi	1
	  stx	_dir_lapin
	__ldwi	200
	__stw	_ball_x
	__ldwi	100
	__stw	_ball_y
	__ldwi	0
	__stw	_ball_vect_x
	__ldwi	0
	__stw	_ball_vect_y
	__ldwi	0
	__stw	_point_alice
	__ldwi	0
	__stw	_point_lapin
	__ldwi	0
	__stw	_play_state
	__ldwi	15
	__stw	_max
	__ldwi	13
	  stx	_al
	__ldwi	0
	  call	_set_font_color.2
	  call	_load_default_font
	__ldw	_point_alice
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldwi	6
	__phb	1
	__ldwi	0
	  call	_put_number.4
	__ldw	_point_lapin
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldwi	24
	__phb	1
	__ldwi	0
	  call	_put_number.4
LL6:

LL7:

LL8:

	  ldy	#0
	  call	_vsync
	__ldw	_counter
	  call	_srand
	__ldwi	0
	  call	_joy
	__stw	_j1
	__ldwi	1
	  call	_joy
	__stw	_j2
	  call	_player_machine
	  call	_score
	  call	_physique
	__ldw	_counter
	incw	_counter
	  ldy	#0
	  call	_satb_update
	__lbra	LL8
LL9:

LL5:

	  rts
	.endp

	.proc _player_machine
	__ldwi	1
	  call	_spr_set
	__ldw	_state_alice
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL11
	  call	_player_alice_0
LL11:

	__ldw	_state_alice
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL12
	  call	_player_alice_1
LL12:

	__ldw	_state_alice
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
	__lbeq	LL13
	  call	_player_alice_2
LL13:

	__ldw	_state_alice
	__stw	<__temp
	__ldwi	3
	  jsr	eqzp
	__lbeq	LL14
	  call	_player_alice_3
LL14:

	__ldw	_state_alice
	__stw	<__temp
	__ldwi	4
	  jsr	eqzp
	__lbeq	LL15
	  call	_player_alice_4
LL15:

	__ldw	_state_alice
	__stw	<__temp
	__ldwi	5
	  jsr	eqzp
	__lbeq	LL16
	  call	_player_alice_5
LL16:

	__ldw	_state_alice
	__stw	<__temp
	__ldwi	6
	  jsr	eqzp
	__lbeq	LL17
	  call	_player_alice_6
LL17:

	__ldwi	0
	  call	_spr_set
	__ldw	_state_lapin
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL18
	  call	_player_lapin_0
LL18:

	__ldw	_state_lapin
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL19
	  call	_player_lapin_1
LL19:

	__ldw	_state_lapin
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
	__lbeq	LL20
	  call	_player_lapin_2
LL20:

	__ldw	_state_lapin
	__stw	<__temp
	__ldwi	3
	  jsr	eqzp
	__lbeq	LL21
	  call	_player_lapin_3
LL21:

	__ldw	_state_lapin
	__stw	<__temp
	__ldwi	4
	  jsr	eqzp
	__lbeq	LL22
	  call	_player_lapin_4
LL22:

	__ldw	_state_lapin
	__stw	<__temp
	__ldwi	5
	  jsr	eqzp
	__lbeq	LL23
	  call	_player_lapin_5
LL23:

	__ldw	_state_lapin
	__stw	<__temp
	__ldwi	6
	  jsr	eqzp
	__lbeq	LL24
	  call	_player_lapin_6
LL24:

LL10:

	  rts
	.endp

	.proc _player_alice_0
	__ldw	_tics_alice
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL26
	__ldwi	25088
	  call	_spr_pattern
LL26:

	__ldwi	1
	__stw	_tics_alice
	__ldw	_j1
	__andwi	128
	__tstw
	__lbeq	LL27
	__ldwi	0
	__stw	_tics_alice
	__ldwi	0
	__stw	_frame_alice
	__ldwi	1
	__stw	_state_alice
	__ldwi	25088
	  call	_spr_pattern
	__ldwi	1
	  stx	_dir_alice
LL27:

	__ldw	_j1
	__andwi	32
	__tstw
	__lbeq	LL28
	__ldwi	0
	__stw	_tics_alice
	__ldwi	0
	__stw	_frame_alice
	__ldwi	1
	__stw	_state_alice
	__ldwi	24576
	  call	_spr_pattern
	__ldwi	2
	  stx	_dir_alice
LL28:

	__ldw	_j1
	__andwi	1
	__tstw
	__lbeq	LL29
	__ldwi	0
	__stw	_tics_alice
	__ldwi	0
	__stw	_frame_alice
	__ldwi	3
	__stw	_state_alice
	__ldwi	24576
	  call	_spr_pattern
LL29:

LL25:

	  rts
	.endp

	.proc _player_alice_1
	__ldwi	0
	  stx	_walk_alice
	__ldw	_tics_alice
	incw	_tics_alice
	__ldw	_tics_alice
	__stw	<__temp
	__ldwi	6
	  jsr	gtzp
	__lbeq	LL31
	__ldwi	0
	__stw	_tics_alice
	__ldw	_frame_alice
	incw	_frame_alice
	__ldw	_frame_alice
	__stw	<__temp
	__ldwi	3
	  jsr	gtzp
	__lbeq	LL32
	__ldwi	0
	__stw	_frame_alice
LL32:

	__ldw	_frame_alice
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL33
	__ldwi	25088
	  call	_spr_pattern
LL33:

	__ldw	_frame_alice
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL34
	__ldwi	24576
	  call	_spr_pattern
LL34:

	__ldw	_frame_alice
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
	__lbeq	LL35
	__ldwi	25088
	  call	_spr_pattern
LL35:

	__ldw	_frame_alice
	__stw	<__temp
	__ldwi	3
	  jsr	eqzp
	__lbeq	LL36
	__ldwi	25600
	  call	_spr_pattern
LL36:

LL31:

	__ldw	_j1
	__andwi	128
	__tstw
	__lbeq	LL38
	__ldb	_dir_alice
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
LL38:

	__boolw
	__tstw
	__lbeq	LL37
	__ldwi	1
	  stx	_walk_alice
LL37:

	__ldw	_j1
	__andwi	32
	__tstw
	__lbeq	LL40
	__ldb	_dir_alice
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
LL40:

	__boolw
	__tstw
	__lbeq	LL39
	__ldwi	1
	  stx	_walk_alice
LL39:

	__ldw	_j1
	__andwi	1
	__tstw
	__lbeq	LL41
	__ldwi	0
	__stw	_tics_alice
	__ldwi	0
	__stw	_frame_alice
	__ldwi	3
	__stw	_state_alice
	__ldwi	24576
	  call	_spr_pattern
LL41:

	__ldb	_walk_alice
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL42
	__ldwi	0
	__stw	_tics_alice
	__ldwi	0
	__stw	_frame_alice
	__ldwi	0
	__stw	_state_alice
	__lbra	LL43
LL42:

	__ldb	_dir_alice
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL44
	__ldw	_alice_x
	__subwi	2
	__stw	_alice_x
	__lbra	LL45
LL44:

	__ldw	_alice_x
	__addwi	2
	__stw	_alice_x
LL45:

LL43:

LL30:

	  rts
	.endp

	.proc _player_alice_2
	__lbra	LL46
LL46:

	  rts
	.endp

	.proc _player_alice_3
	__ldw	_alice_y
	__stw	<__temp
	__ldwi	121
	  jsr	eqzp
	__lbeq	LL48
	__ldwi	10
	__stw	_alice_v
LL48:

	__ldw	_j1
	__andwi	128
	__tstw
	__lbeq	LL49
	__ldwi	1
	  stx	_dir_alice
	__ldw	_alice_x
	__subwi	2
	__stw	_alice_x
LL49:

	__ldw	_j1
	__andwi	32
	__tstw
	__lbeq	LL50
	__ldwi	2
	  stx	_dir_alice
	__ldw	_alice_x
	__addwi	2
	__stw	_alice_x
LL50:

	__ldw	_alice_v
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL51
	__ldwi	4
	__stw	_state_alice
LL51:

LL47:

	  rts
	.endp

	.proc _player_alice_4
	__ldw	_j1
	__andwi	128
	__tstw
	__lbeq	LL53
	__ldwi	1
	  stx	_dir_alice
	__ldw	_alice_x
	__subwi	2
	__stw	_alice_x
LL53:

	__ldw	_j1
	__andwi	32
	__tstw
	__lbeq	LL54
	__ldwi	2
	  stx	_dir_alice
	__ldw	_alice_x
	__addwi	2
	__stw	_alice_x
LL54:

	__ldw	_alice_y
	__stw	<__temp
	__ldwi	121
	  jsr	eqzp
	__lbeq	LL55
	__ldwi	0
	__stw	_state_alice
LL55:

LL52:

	  rts
	.endp

	.proc _player_alice_5
	__lbra	LL56
LL56:

	  rts
	.endp

	.proc _player_alice_6
	__ldwi	1
	__stw	_play_state
	__ldw	_tics_alice
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL58
	__ldwi	26624
	  call	_spr_pattern
LL58:

	__ldw	_tics_alice
	__stw	<__temp
	__ldwi	4
	  jsr	eqzp
	__lbeq	LL59
	__ldwi	26112
	  call	_spr_pattern
LL59:

	__ldw	_tics_alice
	incw	_tics_alice
	__ldw	_tics_alice
	__stw	<__temp
	__ldwi	8
	  jsr	gtzp
	__lbeq	LL60
	__ldwi	0
	__stw	_tics_alice
	__ldwi	0
	__stw	_state_alice
LL60:

LL57:

	  rts
	.endp

	.proc _player_lapin_0
	__ldw	_tics_lapin
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL62
	__ldwi	20992
	  call	_spr_pattern
LL62:

	__ldwi	1
	__stw	_tics_lapin
	__ldw	_j2
	__andwi	128
	__tstw
	__lbeq	LL63
	__ldwi	0
	__stw	_tics_lapin
	__ldwi	0
	__stw	_frame_lapin
	__ldwi	1
	__stw	_state_lapin
	__ldwi	20992
	  call	_spr_pattern
	__ldwi	1
	  stx	_dir_lapin
LL63:

	__ldw	_j2
	__andwi	32
	__tstw
	__lbeq	LL64
	__ldwi	0
	__stw	_tics_lapin
	__ldwi	0
	__stw	_frame_lapin
	__ldwi	1
	__stw	_state_lapin
	__ldwi	20480
	  call	_spr_pattern
	__ldwi	2
	  stx	_dir_lapin
LL64:

	__ldw	_j2
	__andwi	1
	__tstw
	__lbeq	LL65
	__ldwi	0
	__stw	_tics_lapin
	__ldwi	0
	__stw	_frame_lapin
	__ldwi	3
	__stw	_state_lapin
	__ldwi	20480
	  call	_spr_pattern
LL65:

LL61:

	  rts
	.endp

	.proc _player_lapin_1
	__ldwi	0
	  stx	_walk_lapin
	__ldw	_tics_lapin
	incw	_tics_lapin
	__ldw	_tics_lapin
	__stw	<__temp
	__ldwi	6
	  jsr	gtzp
	__lbeq	LL67
	__ldwi	0
	__stw	_tics_lapin
	__ldw	_frame_lapin
	incw	_frame_lapin
	__ldw	_frame_lapin
	__stw	<__temp
	__ldwi	3
	  jsr	gtzp
	__lbeq	LL68
	__ldwi	0
	__stw	_frame_lapin
LL68:

	__ldw	_frame_lapin
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL69
	__ldwi	20992
	  call	_spr_pattern
LL69:

	__ldw	_frame_lapin
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL70
	__ldwi	20480
	  call	_spr_pattern
LL70:

	__ldw	_frame_lapin
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
	__lbeq	LL71
	__ldwi	20992
	  call	_spr_pattern
LL71:

	__ldw	_frame_lapin
	__stw	<__temp
	__ldwi	3
	  jsr	eqzp
	__lbeq	LL72
	__ldwi	21504
	  call	_spr_pattern
LL72:

LL67:

	__ldw	_j2
	__andwi	128
	__tstw
	__lbeq	LL74
	__ldb	_dir_lapin
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
LL74:

	__boolw
	__tstw
	__lbeq	LL73
	__ldwi	1
	  stx	_walk_lapin
LL73:

	__ldw	_j2
	__andwi	32
	__tstw
	__lbeq	LL76
	__ldb	_dir_lapin
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
LL76:

	__boolw
	__tstw
	__lbeq	LL75
	__ldwi	1
	  stx	_walk_lapin
LL75:

	__ldw	_j2
	__andwi	1
	__tstw
	__lbeq	LL77
	__ldwi	0
	__stw	_tics_lapin
	__ldwi	0
	__stw	_frame_lapin
	__ldwi	3
	__stw	_state_lapin
	__ldwi	20480
	  call	_spr_pattern
LL77:

	__ldb	_walk_lapin
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL78
	__ldwi	0
	__stw	_tics_lapin
	__ldwi	0
	__stw	_frame_lapin
	__ldwi	0
	__stw	_state_lapin
	__lbra	LL79
LL78:

	__ldb	_dir_lapin
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL80
	__ldw	_lapin_x
	__subwi	2
	__stw	_lapin_x
	__lbra	LL81
LL80:

	__ldw	_lapin_x
	__addwi	2
	__stw	_lapin_x
LL81:

LL79:

LL66:

	  rts
	.endp

	.proc _player_lapin_2
	__lbra	LL82
LL82:

	  rts
	.endp

	.proc _player_lapin_3
	__ldw	_lapin_y
	__stw	<__temp
	__ldwi	121
	  jsr	eqzp
	__lbeq	LL84
	__ldwi	10
	__stw	_lapin_v
LL84:

	__ldw	_j2
	__andwi	128
	__tstw
	__lbeq	LL85
	__ldwi	1
	  stx	_dir_lapin
	__ldw	_lapin_x
	__subwi	2
	__stw	_lapin_x
LL85:

	__ldw	_j2
	__andwi	32
	__tstw
	__lbeq	LL86
	__ldwi	2
	  stx	_dir_lapin
	__ldw	_lapin_x
	__addwi	2
	__stw	_lapin_x
LL86:

	__ldw	_lapin_v
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL87
	__ldwi	4
	__stw	_state_lapin
LL87:

LL83:

	  rts
	.endp

	.proc _player_lapin_4
	__ldw	_j2
	__andwi	128
	__tstw
	__lbeq	LL89
	__ldwi	1
	  stx	_dir_lapin
	__ldw	_lapin_x
	__subwi	2
	__stw	_lapin_x
LL89:

	__ldw	_j2
	__andwi	32
	__tstw
	__lbeq	LL90
	__ldwi	2
	  stx	_dir_lapin
	__ldw	_lapin_x
	__addwi	2
	__stw	_lapin_x
LL90:

	__ldw	_lapin_y
	__stw	<__temp
	__ldwi	121
	  jsr	eqzp
	__lbeq	LL91
	__ldwi	0
	__stw	_state_lapin
LL91:

LL88:

	  rts
	.endp

	.proc _player_lapin_5
	__lbra	LL92
LL92:

	  rts
	.endp

	.proc _player_lapin_6
	__ldwi	1
	__stw	_play_state
	__ldw	_tics_lapin
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL94
	__ldwi	22528
	  call	_spr_pattern
LL94:

	__ldw	_tics_lapin
	__stw	<__temp
	__ldwi	4
	  jsr	eqzp
	__lbeq	LL95
	__ldwi	22016
	  call	_spr_pattern
LL95:

	__ldw	_tics_lapin
	incw	_tics_lapin
	__ldw	_tics_lapin
	__stw	<__temp
	__ldwi	8
	  jsr	gtzp
	__lbeq	LL96
	__ldwi	0
	__stw	_tics_lapin
	__ldwi	0
	__stw	_state_lapin
LL96:

LL93:

	  rts
	.endp

	.proc _physique
	__ldw	_alice_x
	__pushw
	__ldwi	8
	__negw
	  jsr	lt
	__lbeq	LL98
	__ldwi	8
	__negw
	__stw	_alice_x
LL98:

	__ldw	_alice_x
	__stw	<__temp
	__ldwi	96
	  jsr	gtzp
	__lbeq	LL99
	__ldwi	96
	__stw	_alice_x
LL99:

	__ldw	_alice_y
	__subw	_alice_v
	__stw	_alice_y
	__ldw	_alice_y
	__stw	<__temp
	__ldwi	121
	  jsr	ltzp
	__lbeq	LL100
	__ldw	_alice_v
	__subwi	1
	__stw	_alice_v
	__addwi	1
LL100:

	__ldw	_alice_y
	__stw	<__temp
	__ldwi	121
	  jsr	gtzp
	__lbeq	LL101
	__ldwi	121
	__stw	_alice_y
LL101:

	__ldwi	1
	__pushw
	__ldw	_alice_x
	__pushw
	__ldw	_alice_y
	__pushw
	__ldb	_dir_alice
	  call	_spr_put
	__ldw	_lapin_x
	__stw	<__temp
	__ldwi	128
	  jsr	ltzp
	__lbeq	LL102
	__ldwi	128
	__stw	_lapin_x
LL102:

	__ldw	_lapin_x
	__stw	<__temp
	__ldwi	232
	  jsr	gtzp
	__lbeq	LL103
	__ldwi	232
	__stw	_lapin_x
LL103:

	__ldw	_lapin_y
	__subw	_lapin_v
	__stw	_lapin_y
	__ldw	_lapin_y
	__stw	<__temp
	__ldwi	121
	  jsr	ltzp
	__lbeq	LL104
	__ldw	_lapin_v
	__subwi	1
	__stw	_lapin_v
	__addwi	1
LL104:

	__ldw	_lapin_y
	__stw	<__temp
	__ldwi	121
	  jsr	gtzp
	__lbeq	LL105
	__ldwi	121
	__stw	_lapin_y
LL105:

	__ldwi	0
	__pushw
	__ldw	_lapin_x
	__pushw
	__ldw	_lapin_y
	__pushw
	__ldb	_dir_lapin
	  call	_spr_put
	__ldwi	4
	__pushw
	__ldwi	112
	__pushw
	__ldwi	121
	__pushw
	__ldwi	15
	  call	_rebond
	__ldwi	1
	__pushw
	__ldw	_alice_x
	__pushw
	__ldw	_alice_y
	__pushw
	__ldwi	15
	  call	_rebond
	__ldwi	0
	__pushw
	__ldw	_lapin_x
	__pushw
	__ldw	_lapin_y
	__pushw
	__ldwi	15
	  call	_rebond
	__ldw	_play_state
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL106
	__ldw	_ball_y
	__pushw
	__ldw	_ball_vect_y
	__pushw
	__ldwi	4
	  jsr	sdiv
	__subws
	__stw	_ball_y
	__ldw	_ball_vect_y
	__subwi	1
	__stw	_ball_vect_y
	__addwi	1
	__ldw	_ball_x
	__pushw
	__ldw	_ball_vect_x
	__pushw
	__ldwi	4
	  jsr	sdiv
	__addws
	__stw	_ball_x
	__ldw	_ball_x
	__stw	<__temp
	__ldwi	248
	  jsr	gtzp
	__lbeq	LL107
	__ldw	_ball_vect_x
	__negw
	__stw	_ball_vect_x
LL107:

	__ldw	_ball_x
	__pushw
	__ldwi	8
	__negw
	  jsr	lt
	__lbeq	LL108
	__ldw	_ball_vect_x
	__negw
	__stw	_ball_vect_x
LL108:

LL106:

	__ldwi	2
	__pushw
	__ldw	_ball_x
	__pushw
	__ldw	_ball_y
	__pushw
	__ldwi	1
	  call	_spr_put
LL97:

	  rts
	.endp

	.proc _rebond
	__pushw
	__addmi	-2,__stack
	__ldw	_ball_x
	__subwi	8
	__pushw
	__ldw_s	8
	__subws
	__stw_s	0
	__pushw
	__ldwi	20
	__negw
	  jsr	gt
	__pushw
	__ldw_s	2
	__stw	<__temp
	__ldwi	20
	  jsr	ltzp
	__andws
	__pushw
	__ldw	_ball_y
	__pushw
	__ldw_s	8
	__addwi	8
	__subwi	22
	  jsr	gt
	__andws
	__tstw
	__lbeq	LL110
	__ldw_s	2
	__pushw
	__ldwi	4
	__pushw
	__ldwi	2
	  jsr	sdiv
	  jsr	smul
	__stw	_ball_vect_y
	__ldw_s	0
	__pushw
	__ldwi	4
	__pushw
	__ldwi	2
	  jsr	sdiv
	  jsr	smul
	__stw	_ball_vect_x
	__ldw_s	8
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL111
	__ldwi	6
	__stw	_state_lapin
	__ldwi	0
	__stw	_tics_lapin
LL111:

	__ldw_s	8
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL112
	__ldwi	6
	__stw	_state_alice
	__ldwi	0
	__stw	_tics_alice
LL112:

LL110:

LL109:

	__addmi	10,__stack
	  rts
	.endp

	.proc _score
	__ldw	_point_alice
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__pushw
	__ldw	_point_lapin
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__andws
	__pushw
	__ldw	_play_state
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__andws
	__tstw
	__lbeq	LL114
	__ldwi	120
	__stw	_ball_x
	__ldwi	50
	__stw	_ball_y
	__ldw	_j1
	__pushw
	__ldw	_j2
	__orws
	__andwi	8
	__tstw
	__lbeq	LL115
	__ldwi	21
	  call	_random
	__subwi	10
	__pushw
	__ldwi	4
	__pushw
	__ldwi	2
	  jsr	sdiv
	  jsr	smul
	__stw	_ball_vect_x
	__ldwi	15
	__stw	_ball_vect_y
	__ldwi	1
	__stw	_play_state
LL115:

LL114:

	__ldw	_ball_y
	__stw	<__temp
	__ldwi	150
	  jsr	gtzp
	__lbeq	LL116
	__ldwi	0
	__stw	_ball_vect_x
	__ldwi	0
	__stw	_ball_vect_y
	__ldwi	80
	__stw	_ball_y
	__ldwi	0
	__stw	_play_state
	__ldw	_ball_x
	__stw	<__temp
	__ldwi	128
	  jsr	ltzp
	__lbeq	LL117
	__ldw	_point_lapin
	incw	_point_lapin
	__ldwi	198
	__stw	_ball_x
	__lbra	LL118
LL117:

	__ldw	_point_alice
	incw	_point_alice
	__ldwi	42
	__stw	_ball_x
LL118:

	__ldw	_point_alice
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldwi	6
	__phb	1
	__ldwi	0
	  call	_put_number.4
	__ldw	_point_lapin
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldwi	24
	__phb	1
	__ldwi	0
	  call	_put_number.4
LL116:

	__ldw	_point_alice
	__stw	<__temp
	__ldw	_max
	  jsr	eqzp
	__pushw
	__ldw	_point_lapin
	__stw	<__temp
	__ldw	_max
	  jsr	eqzp
	__orws
	__tstw
	__lbeq	LL119
	__ldwi	0
	__stw	_point_alice
	__ldwi	0
	__stw	_point_lapin
	__ldwi	0
	__stw	_play_state
	__ldw	_point_alice
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldwi	6
	__phb	1
	__ldwi	0
	  call	_put_number.4
	__ldw	_point_lapin
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldwi	24
	__phb	1
	__ldwi	0
	  call	_put_number.4
LL119:

LL113:

	  rts
	.endp


	.bss
_tics_alice:		.ds	2
_frame_alice:		.ds	2
_state_alice:		.ds	2
_tics_lapin:		.ds	2
_frame_lapin:		.ds	2
_state_lapin:		.ds	2
_counter:		.ds	2
_j1:		.ds	2
_j2:		.ds	2
_alice_x:		.ds	2
_alice_y:		.ds	2
_alice_v:		.ds	2
_lapin_x:		.ds	2
_lapin_y:		.ds	2
_lapin_v:		.ds	2
_ball_x:		.ds	2
_ball_y:		.ds	2
_ball_vect_x:		.ds	2
_ball_vect_y:		.ds	2
_point_alice:		.ds	2
_point_lapin:		.ds	2
_play_state:		.ds	2
_max:		.ds	2
_dir_alice:		.ds	1
_dir_lapin:		.ds	1
_walk_alice:		.ds	1
_walk_lapin:		.ds	1
__arg:

;0 error(s) in compilation
;	literal pool:0
;	constant pool:0
;	global pool:2560
;	Macro pool:1103
