; Small C HuC6280 (v0.2, 08/Nov/97)
;
; Taken to HuC (22/Feb/00)
;
;
; This file generated by HuC (v3.21, 2005/04/09, Denki release)
; on Mon Apr  6 12:28:43 2015
;

HUC	= 1

	.include "startup.asm"
	.data
	.bank DATA_BANK

	.code

	.proc _spr_make
	__pushw
	__ldw_s	14
	  call	_spr_set
	__ldw_s	12
	  call	_spr_x
	__ldw_s	10
	  call	_spr_y
	__ldw_s	8
	  call	_spr_pattern
	__ldw_s	6
	  stx	_al
	__ldw_s	4
	  call	_spr_ctrl.2
	__ldw_s	2
	  call	_spr_pal
	__ldw_s	0
	  call	_spr_pri
LL1:

	__addmi	16,__stack
	  rts
	.endp

	.proc _spr_put
	__pushw
	__ldw_s	6
	  call	_spr_set
	__ldw_s	4
	  call	_spr_x
	__ldw_s	2
	  call	_spr_y
	__ldw_s	0
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL3
	__ldwi	8
	  stx	_al
	__ldwi	8
	  call	_spr_ctrl.2
	__lbra	LL4
LL3:

	__ldwi	8
	  stx	_al
	__ldwi	0
	  call	_spr_ctrl.2
LL4:

LL2:

	__addmi	8,__stack
	  rts
	.endp

	.data
	.dw $0
_alice:
	.incspr "alice.pcx",0,0,2,20
	.code
	.data
	.dw $0
_alicepal:
	.incpal "alice.pcx"
	.code
	.data
	.dw $0
_lapin:
	.incspr "lapin.pcx",0,0,2,20
	.code
	.data
	.dw $0
_lapinpal:
	.incpal "lapin.pcx"
	.code
	.data
	.dw $0
_ball:
	.incspr "ball.pcx",0,0,1,1
	.code
	.data
	.dw $0
_ballpal:
	.incpal "ball.pcx"
	.code
	.data
	.dw $0800
_scene_chr:
	.incchr "background_ground.pcx"
	.code
	.data
	.dw $0
_scene_pal:
	.incpal "background_ground.pcx"
	.code
	.data
	.dw $0
_scene_bat:
	.incbat "background_ground.pcx",4096,32,28
	.code
	.proc _main
	__ldwi	0
	__pushw
	__ldwi	180
	__pushw
	__ldwi	121
	__pushw
	__ldwi	20480
	__pushw
	__ldwi	185
	__pushw
	__ldwi	49
	__pushw
	__ldwi	0
	__pushw
	__ldwi	1
	  call	_spr_make
	_set_sprpal	#0,_lapinpal,#1
	__ldwi	20480
	__stw	_di
	__farptr	_lapin,_bl,_si
	__ldwi	1536
	__stw	_cx
	  call	_load_vram.3
	__ldwi	1
	__pushw
	__ldwi	52
	__pushw
	__ldwi	121
	__pushw
	__ldwi	25088
	__pushw
	__ldwi	185
	__pushw
	__ldwi	49
	__pushw
	__ldwi	1
	__pushw
	__ldwi	1
	  call	_spr_make
	_set_sprpal	#1,_alicepal,#1
	__ldwi	24576
	__stw	_di
	__farptr	_alice,_bl,_si
	__ldwi	4096
	__stw	_cx
	  call	_load_vram.3
	__ldwi	2
	__pushw
	__ldwi	200
	__pushw
	__ldwi	100
	__pushw
	__ldwi	22784
	__pushw
	__ldwi	185
	__pushw
	__ldwi	0
	__pushw
	__ldwi	2
	__pushw
	__ldwi	1
	  call	_spr_make
	_set_sprpal	#2,_ballpal,#1
	__ldwi	22784
	__stw	_di
	__farptr	_ball,_bl,_si
	__ldwi	256
	__stw	_cx
	  call	_load_vram.3
	_load_background	_scene_chr,_scene_pal,_scene_bat,#32,#28
	__ldwi	0
	__stw	_counter
	__ldwi	0
	__stw	_tics_alice
	__ldwi	0
	__stw	_frame_alice
	__ldwi	0
	__stw	_state_alice
	__ldwi	0
	__stw	_tics_lapin
	__ldwi	0
	__stw	_frame_lapin
	__ldwi	0
	__stw	_state_lapin
	__ldwi	52
	__stw	_alice_x
	__ldwi	180
	__stw	_lapin_x
	__ldwi	121
	__stw	_alice_y
	__ldwi	121
	__stw	_lapin_y
	__ldwi	0
	__stw	_alice_v
	__ldwi	0
	__stw	_lapin_v
	__ldwi	200
	__stw	_ball_x
	__ldwi	100
	__stw	_ball_y
	__ldwi	0
	__stw	_ball_vect_x
	__ldwi	0
	__stw	_ball_vect_y
	__ldwi	0
	__stw	_point_alice
	__ldwi	0
	__stw	_point_lapin
	__ldwi	0
	__stw	_play_state
	__ldwi	13
	  stx	_al
	__ldwi	0
	  call	_set_font_color.2
	  call	_load_default_font
	__ldw	_point_alice
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldwi	6
	__phb	1
	__ldwi	0
	  call	_put_number.4
	__ldw	_point_lapin
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldwi	24
	__phb	1
	__ldwi	0
	  call	_put_number.4
LL6:

LL7:

LL8:

	  ldy	#0
	  call	_vsync
	__ldw	_counter
	  call	_srand
	__ldwi	0
	  call	_joy
	__stw	_j1
	__ldwi	1
	  call	_joy
	__stw	_j2
	  call	_player_machine
	  call	_score
	  call	_physique
	__ldw	_ball_vect_x
	__phw	4,4
	__ldwi	5
	__phb	2
	__ldwi	5
	__phb	1
	__ldwi	3
	  call	_put_number.4
	__ldw	_counter
	incw	_counter
	  ldy	#0
	  call	_satb_update
	__lbra	LL8
LL9:

LL5:

	  rts
	.endp

	.proc _player_machine
	__ldwi	1
	  call	_spr_set
	__ldw	_state_alice
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL11
	  call	_player_alice_0
LL11:

	__ldw	_state_alice
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL12
	  call	_player_alice_1
LL12:

	__ldw	_state_alice
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
	__lbeq	LL13
	  call	_player_alice_2
LL13:

	__ldw	_state_alice
	__stw	<__temp
	__ldwi	3
	  jsr	eqzp
	__lbeq	LL14
	  call	_player_alice_3
LL14:

	__ldw	_state_alice
	__stw	<__temp
	__ldwi	4
	  jsr	eqzp
	__lbeq	LL15
	  call	_player_alice_4
LL15:

	__ldw	_state_alice
	__stw	<__temp
	__ldwi	5
	  jsr	eqzp
	__lbeq	LL16
	  call	_player_alice_5
LL16:

	__ldw	_state_alice
	__stw	<__temp
	__ldwi	6
	  jsr	eqzp
	__lbeq	LL17
	  call	_player_alice_6
LL17:

LL10:

	  rts
	.endp

	.proc _player_alice_0
	__ldw	_tics_alice
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL19
	__ldwi	25088
	  call	_spr_pattern
LL19:

	__ldwi	1
	__stw	_tics_alice
	__ldw	_j1
	__andwi	128
	__tstw
	__lbeq	LL20
	__ldwi	0
	__stw	_tics_alice
	__ldwi	0
	__stw	_frame_alice
	__ldwi	1
	__stw	_state_alice
	__ldwi	25088
	  call	_spr_pattern
	__ldwi	1
	  stx	_dir_alice
LL20:

	__ldw	_j1
	__andwi	32
	__tstw
	__lbeq	LL21
	__ldwi	0
	__stw	_tics_alice
	__ldwi	0
	__stw	_frame_alice
	__ldwi	1
	__stw	_state_alice
	__ldwi	24576
	  call	_spr_pattern
	__ldwi	2
	  stx	_dir_alice
LL21:

	__ldw	_j1
	__andwi	1
	__tstw
	__lbeq	LL22
	__ldwi	0
	__stw	_tics_alice
	__ldwi	0
	__stw	_frame_alice
	__ldwi	3
	__stw	_state_alice
	__ldwi	24576
	  call	_spr_pattern
LL22:

LL18:

	  rts
	.endp

	.proc _player_alice_1
	__ldwi	0
	  stx	_walk_alice
	__ldw	_tics_alice
	incw	_tics_alice
	__ldw	_tics_alice
	__stw	<__temp
	__ldwi	6
	  jsr	gtzp
	__lbeq	LL24
	__ldwi	0
	__stw	_tics_alice
	__ldw	_frame_alice
	incw	_frame_alice
	__ldw	_frame_alice
	__stw	<__temp
	__ldwi	3
	  jsr	gtzp
	__lbeq	LL25
	__ldwi	0
	__stw	_frame_alice
LL25:

	__ldw	_frame_alice
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL26
	__ldwi	25088
	  call	_spr_pattern
LL26:

	__ldw	_frame_alice
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL27
	__ldwi	24576
	  call	_spr_pattern
LL27:

	__ldw	_frame_alice
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
	__lbeq	LL28
	__ldwi	25088
	  call	_spr_pattern
LL28:

	__ldw	_frame_alice
	__stw	<__temp
	__ldwi	3
	  jsr	eqzp
	__lbeq	LL29
	__ldwi	25600
	  call	_spr_pattern
LL29:

LL24:

	__ldw	_j1
	__andwi	128
	__tstw
	__lbeq	LL31
	__ldb	_dir_alice
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
LL31:

	__boolw
	__tstw
	__lbeq	LL30
	__ldwi	1
	  stx	_walk_alice
LL30:

	__ldw	_j1
	__andwi	32
	__tstw
	__lbeq	LL33
	__ldb	_dir_alice
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
LL33:

	__boolw
	__tstw
	__lbeq	LL32
	__ldwi	1
	  stx	_walk_alice
LL32:

	__ldw	_j1
	__andwi	1
	__tstw
	__lbeq	LL34
	__ldwi	0
	__stw	_tics_alice
	__ldwi	0
	__stw	_frame_alice
	__ldwi	3
	__stw	_state_alice
	__ldwi	24576
	  call	_spr_pattern
LL34:

	__ldb	_walk_alice
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL35
	__ldwi	0
	__stw	_tics_alice
	__ldwi	0
	__stw	_frame_alice
	__ldwi	0
	__stw	_state_alice
	__lbra	LL36
LL35:

	__ldb	_dir_alice
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL37
	__ldw	_alice_x
	__subwi	2
	__stw	_alice_x
	__lbra	LL38
LL37:

	__ldw	_alice_x
	__addwi	2
	__stw	_alice_x
LL38:

LL36:

LL23:

	  rts
	.endp

	.proc _player_alice_2
	__lbra	LL39
LL39:

	  rts
	.endp

	.proc _player_alice_3
	__ldw	_alice_y
	__stw	<__temp
	__ldwi	121
	  jsr	eqzp
	__lbeq	LL41
	__ldwi	10
	__stw	_alice_v
LL41:

	__ldw	_j1
	__andwi	128
	__tstw
	__lbeq	LL42
	__ldwi	1
	  stx	_dir_alice
	__ldw	_alice_x
	__subwi	2
	__stw	_alice_x
LL42:

	__ldw	_j1
	__andwi	32
	__tstw
	__lbeq	LL43
	__ldwi	2
	  stx	_dir_alice
	__ldw	_alice_x
	__addwi	2
	__stw	_alice_x
LL43:

	__ldw	_alice_v
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL44
	__ldwi	4
	__stw	_state_alice
LL44:

LL40:

	  rts
	.endp

	.proc _player_alice_4
	__ldw	_j1
	__andwi	128
	__tstw
	__lbeq	LL46
	__ldwi	1
	  stx	_dir_alice
	__ldw	_alice_x
	__subwi	2
	__stw	_alice_x
LL46:

	__ldw	_j1
	__andwi	32
	__tstw
	__lbeq	LL47
	__ldwi	2
	  stx	_dir_alice
	__ldw	_alice_x
	__addwi	2
	__stw	_alice_x
LL47:

	__ldw	_alice_y
	__stw	<__temp
	__ldwi	121
	  jsr	eqzp
	__lbeq	LL48
	__ldwi	0
	__stw	_state_alice
LL48:

LL45:

	  rts
	.endp

	.proc _player_alice_5
	__lbra	LL49
LL49:

	  rts
	.endp

	.proc _player_alice_6
	__ldwi	1
	__stw	_play_state
	__ldw	_tics_alice
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL51
	__ldwi	26624
	  call	_spr_pattern
LL51:

	__ldw	_tics_alice
	__stw	<__temp
	__ldwi	4
	  jsr	eqzp
	__lbeq	LL52
	__ldwi	26112
	  call	_spr_pattern
LL52:

	__ldw	_tics_alice
	incw	_tics_alice
	__ldw	_tics_alice
	__stw	<__temp
	__ldwi	8
	  jsr	gtzp
	__lbeq	LL53
	__ldwi	0
	__stw	_tics_alice
	__ldwi	0
	__stw	_state_alice
LL53:

LL50:

	  rts
	.endp

	.proc _physique
	__ldw	_alice_x
	__pushw
	__ldwi	8
	__negw
	  jsr	lt
	__lbeq	LL55
	__ldwi	8
	__negw
	__stw	_alice_x
LL55:

	__ldw	_alice_x
	__stw	<__temp
	__ldwi	96
	  jsr	gtzp
	__lbeq	LL56
	__ldwi	96
	__stw	_alice_x
LL56:

	__ldw	_alice_y
	__subw	_alice_v
	__stw	_alice_y
	__ldw	_alice_y
	__stw	<__temp
	__ldwi	121
	  jsr	ltzp
	__lbeq	LL57
	__ldw	_alice_v
	__subwi	1
	__stw	_alice_v
	__addwi	1
LL57:

	__ldw	_alice_y
	__stw	<__temp
	__ldwi	121
	  jsr	gtzp
	__lbeq	LL58
	__ldwi	121
	__stw	_alice_y
LL58:

	__ldwi	1
	__pushw
	__ldw	_alice_x
	__pushw
	__ldw	_alice_y
	__pushw
	__ldb	_dir_alice
	  call	_spr_put
	__ldwi	4
	__pushw
	__ldwi	112
	__pushw
	__ldwi	121
	__pushw
	__ldwi	15
	  call	_rebond
	__ldwi	1
	__pushw
	__ldw	_alice_x
	__pushw
	__ldw	_alice_y
	__pushw
	__ldwi	15
	  call	_rebond
	__ldwi	0
	__pushw
	__ldw	_lapin_x
	__pushw
	__ldw	_lapin_y
	__pushw
	__ldwi	15
	  call	_rebond
	__ldw	_play_state
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL59
	__ldw	_ball_y
	__pushw
	__ldw	_ball_vect_y
	__pushw
	__ldwi	4
	  jsr	sdiv
	__subws
	__stw	_ball_y
	__ldw	_ball_vect_y
	__subwi	1
	__stw	_ball_vect_y
	__addwi	1
	__ldw	_ball_x
	__pushw
	__ldw	_ball_vect_x
	__pushw
	__ldwi	4
	  jsr	sdiv
	__addws
	__stw	_ball_x
	__ldw	_ball_x
	__stw	<__temp
	__ldwi	248
	  jsr	gtzp
	__lbeq	LL60
	__ldw	_ball_vect_x
	__negw
	__stw	_ball_vect_x
LL60:

	__ldw	_ball_x
	__pushw
	__ldwi	8
	__negw
	  jsr	lt
	__lbeq	LL61
	__ldw	_ball_vect_x
	__negw
	__stw	_ball_vect_x
LL61:

LL59:

	__ldwi	2
	__pushw
	__ldw	_ball_x
	__pushw
	__ldw	_ball_y
	__pushw
	__ldwi	1
	  call	_spr_put
LL54:

	  rts
	.endp

	.proc _rebond
	__pushw
	__addmi	-2,__stack
	__ldw	_ball_x
	__subwi	8
	__pushw
	__ldw_s	8
	__subws
	__stw_s	0
	__pushw
	__ldwi	20
	__negw
	  jsr	gt
	__pushw
	__ldw_s	2
	__stw	<__temp
	__ldwi	20
	  jsr	ltzp
	__andws
	__pushw
	__ldw	_ball_y
	__pushw
	__ldw_s	8
	__addwi	8
	__subwi	22
	  jsr	gt
	__andws
	__tstw
	__lbeq	LL63
	__ldw_s	2
	__pushw
	__ldwi	4
	__pushw
	__ldwi	2
	  jsr	sdiv
	  jsr	smul
	__stw	_ball_vect_y
	__ldw_s	0
	__pushw
	__ldwi	4
	__pushw
	__ldwi	2
	  jsr	sdiv
	  jsr	smul
	__stw	_ball_vect_x
	__ldw_s	8
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL64
	__ldwi	6
	__stw	_state_alice
	__ldwi	0
	__stw	_tics_alice
LL64:

LL63:

LL62:

	__addmi	10,__stack
	  rts
	.endp

	.proc _score
	__ldw	_point_alice
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__pushw
	__ldw	_point_lapin
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__andws
	__pushw
	__ldw	_play_state
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__andws
	__tstw
	__lbeq	LL66
	__ldwi	120
	__stw	_ball_x
	__ldwi	50
	__stw	_ball_y
	__ldw	_j1
	__pushw
	__ldw	_j2
	__orws
	__andwi	8
	__tstw
	__lbeq	LL67
	__ldwi	21
	  call	_random
	__subwi	10
	__pushw
	__ldwi	4
	__pushw
	__ldwi	2
	  jsr	sdiv
	  jsr	smul
	__stw	_ball_vect_x
	__ldwi	15
	__stw	_ball_vect_y
	__ldwi	1
	__stw	_play_state
LL67:

	__lbra	LL68
LL66:

	__ldw	_ball_y
	__stw	<__temp
	__ldwi	150
	  jsr	gtzp
	__lbeq	LL69
	__ldwi	0
	__stw	_ball_vect_x
	__ldwi	0
	__stw	_ball_vect_y
	__ldwi	80
	__stw	_ball_y
	__ldwi	0
	__stw	_play_state
	__ldw	_ball_x
	__stw	<__temp
	__ldwi	128
	  jsr	ltzp
	__lbeq	LL70
	__ldw	_point_lapin
	incw	_point_lapin
	__ldwi	198
	__stw	_ball_x
	__lbra	LL71
LL70:

	__ldw	_point_alice
	incw	_point_alice
	__ldwi	42
	__stw	_ball_x
LL71:

	__ldw	_point_alice
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldwi	6
	__phb	1
	__ldwi	0
	  call	_put_number.4
	__ldw	_point_lapin
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldwi	24
	__phb	1
	__ldwi	0
	  call	_put_number.4
LL69:

LL68:

LL65:

	  rts
	.endp


	.bss
_tics_alice:		.ds	2
_frame_alice:		.ds	2
_state_alice:		.ds	2
_tics_lapin:		.ds	2
_frame_lapin:		.ds	2
_state_lapin:		.ds	2
_counter:		.ds	2
_j1:		.ds	2
_j2:		.ds	2
_alice_x:		.ds	2
_alice_y:		.ds	2
_alice_v:		.ds	2
_lapin_x:		.ds	2
_lapin_y:		.ds	2
_lapin_v:		.ds	2
_ball_x:		.ds	2
_ball_y:		.ds	2
_ball_vect_x:		.ds	2
_ball_vect_y:		.ds	2
_point_alice:		.ds	2
_point_lapin:		.ds	2
_play_state:		.ds	2
_dir_alice:		.ds	1
_dir_lapin:		.ds	1
_walk_alice:		.ds	1
_walk_lapin:		.ds	1
__arg:

;0 error(s) in compilation
;	literal pool:0
;	constant pool:0
;	global pool:2304
;	Macro pool:1103
